name: Build and Test with JDK 22

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openjdk:22-ea-jdk
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Java version
        run: java -version

      - name: Set mvnw permissions
        if: exists('mvnw')
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar